### ISSUE TITLE
NameError: free variable 'betaStr' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by malmarri** [35ajstern/palm#1]
Hi Aaron,
I ran palm as shown in the example, after downloading the trait metadata/sumstats & SNP likelihoods from datadryad, but recieve the following 'NameError': 
```

python3  palm.py --traitDir 1000G_SNPs/ --metadata sumstats_05062020/marginal/Hb1A1c.neale_both_sexes.tsv --maxp 5e-8 --B 1000
Traceback (most recent call last):
  File "palm.py", line 287, in <module>
    _main(args)
  File "palm.py", line 257, in _main
    statistics = _parse_loci_stats(args)
  File "palm.py", line 56, in _parse_loci_stats
    traitNames = [col[len(betaStr):] for col in betaColumns]
  File "palm.py", line 56, in <listcomp>
    traitNames = [col[len(betaStr):] for col in betaColumns]
NameError: free variable 'betaStr' referenced before assignment in enclosing scope
```
Do you have any suggestions on how to solve this?

Thanks,
Mo

**Comment by 35ajstern** [comment]
Thanks for pointing this out. Can you perform a pull and see whether the newest commit fixes the issue (which seems to be for analyses of single traits, here e.g. HbA1c)?

Aaron

**Comment by malmarri** [comment]
It starts to run but a new error appears
```

python3 palm.py --traitDir 1000G_SNPs/ --metadata sumstats_05062020/marginal/Hb1A1c.neale_both_sexes.tsv --maxp 5e-8 --B 1000

Analyzing trait...
Loading likelihoods...
[=========================================================================================================================================================] 100%
Analyzing 174 loci...
Traceback (most recent call last):
  File "palm.py", line 291, in <module>
    _main(args)
  File "palm.py", line 272, in _main
    omega,ses = _inference(statistics,args)	
  File "palm.py", line 195, in _inference
    if args.bootstrap:
AttributeError: 'Namespace' object has no attribute 'bootstrap'

```

**Comment by 35ajstern** [comment]
Weird - i think the versioning got screwed up somehow and there are a couple of calls to options from a previous version that are no longer defined.

Can you try again? Thanks,

Aaron

**Comment by malmarri** [comment]
Works fine now, thanks.
